Repository polzzak-by-nowashgirls/polzzak, pull requests merged in 2025-05, with the labels that each got.

#175 [Feature] 지도 모달 기능 구현
  public/icons/sprite.svg
  public/marker/map_cultural.svg
  public/marker/map_favorite.svg
  public/marker/map_festival.svg
  public/marker/map_food.svg
  public/marker/map_hotels.svg
  public/marker/map_leports.svg
  public/marker/map_marker_favorite.svg
  public/marker/map_marker_festival.svg
  public/marker/map_marker_food.svg
  public/marker/map_marker_polzzak.svg
  public/marker/map_marker_tour.svg
  public/marker/map_polzzak.svg
  public/marker/map_shopping.svg
  public/marker/map_tour.svg
  public/marker/my_location.svg
  src/api/openAPI/hooks/map/useGetNearCategoryList.ts
  src/api/openAPI/hooks/map/useGetNearData.ts
  src/api/openAPI/hooks/map/useGetNearFestivalList.ts
  src/api/openAPI/hooks/map/useGetNearFoodList.ts
  src/api/openAPI/hooks/map/useGetNearTourList.ts
  src/components/Dialog/SlideUpDialog.tsx
  src/components/Icon/Icon.tsx
  src/components/Map/MapHeader.tsx
  src/components/Map/ModalContent.tsx
  src/pages/Contents/Contents.tsx
  src/pages/Contents/ViewDetails.tsx
  src/pages/Map/Map.tsx
  src/types/LatLng.ts
  src/types/detailCommonDataType.ts
Labels: ♻️ Refactor, ✒️ Modify, ✅ Feature

#177 [Feature] 로그인 기능 구현
  src/components/Map/MapHeader.tsx
  src/layouts/RootLayout.tsx
  src/pages/Login/Login.tsx
  src/pages/Map/Map.tsx
  src/store/useAuthStore.ts
Labels: ✒️ Modify, ✅ Feature

#179 [Feature] 아이디, 비밀번호 찾기 기능 구현
  src/layouts/RootLayout.tsx
  src/lib/validationEmail.ts
  src/pages/Login/FindId.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/ResetPassword.tsx
  src/pages/Login/ResetPasswordCallback.tsx
  src/pages/index.ts
  src/router.tsx
  src/store/useDialogStore.ts
  src/styles/globals.css
Labels: ✒️ Modify, ✅ Feature

#180 [Feature] 폴짝 페이지 기능(추가, 편집, 리스트)
  package.json
  pnpm-lock.yaml
  public/images/backpack.png
  public/images/flag.png
  src/components/Input/ImageCropper.tsx
  src/components/Input/Input.tsx
  src/components/Input/Textarea.tsx
  src/components/Polzzak/PolzzakList.tsx
  src/components/Polzzak/PolzzakListItem.tsx
  src/components/Polzzak/PolzzakSection.tsx
  src/components/Timeline/TimelineCard.tsx
  src/components/Timeline/TimelineList.tsx
  src/components/Timeline/TimelineSchedule.tsx
  src/layouts/RootLayout.tsx
  src/lib/getCroppedImg.ts
  src/mockData/PolzzakItemDummyData.tsx
  src/mockData/PolzzakListDummyData.tsx
  src/pages/My/Favorites/Favorites.tsx
  src/pages/Polzzak/Add/Add.tsx
  src/pages/Polzzak/AddNEdit/AddNEdit.tsx
  src/pages/Polzzak/Edit/Edit.tsx
  src/pages/Polzzak/Polzzak.tsx
  src/pages/Polzzak/Schedule/Schedule.tsx
  src/pages/Polzzak/index.ts
  src/router.tsx
  src/store/useDialogStore.ts
  src/store/usePolzzakStroe.ts
Labels: ♻️ Refactor, ✒️ Modify, ✅ Feature, ✂️ Rename, ⛔ Remove

#183 [Modify] 다이얼로그 컴포넌트 수정
  src/components/Dialog/SlideUpDialog.tsx
Labels: ✒️ Modify

#185 [Feature] 지도 페이지 기능 구현
  src/api/openAPI/utils/fetchContentDetail.ts
  src/components/Map/DetailItems.ts
  src/components/Map/ModalContent.tsx
  src/components/Map/ModalDetailContent.tsx
  src/lib/formatBr.tsx
  src/lib/formatDate.ts
  src/pages/Map/Map.tsx
  src/types/categoryDetailType.ts
Labels: ✒️ Modify, ✅ Feature

#186 [Feature] 폴짝 페이지 기능 완료 (지도에서 장소 저장 제외)
  src/components/Calendar/CalendarCustom.tsx
  src/components/Input/Input.tsx
  src/components/Timeline/Plan.tsx
  src/components/Timeline/TimelineCard.tsx
  src/components/Timeline/TimelineList.tsx
  src/components/Timeline/TimelineSchedule.tsx
  src/pages/Polzzak/Schedule/AddPlan/AddPlan.tsx
  src/pages/Polzzak/Schedule/Schedule.tsx
  src/pages/Polzzak/index.ts
  src/router.tsx
Labels: ✒️ Modify, ✅ Feature

#193 [Fix] 배포 시 오류 수정
  src/components/Modal/Modal.tsx
  src/components/Modal/SlideUpModal.tsx
  src/hooks/useModalActions.ts
  src/pages/My/Edit/PhoneNumber/PhoneNumber.tsx
  src/pages/Register/Step3.tsx
  src/pages/Search/Search.tsx
  src/store/useEditStore.ts
  src/store/useModalStore.ts
  src/store/usePasswordStore.ts
Labels: 🛠️ Fix

#194 [Fix] 린트 결과 수정
  src/api/openAPI/hooks/useGetFestival.ts
  src/components/Favorites/FavoritesList.tsx
  src/components/ListItem/ListItemCardById.tsx
  src/pages/Polzzak/AddNEdit/AddNEdit.tsx
  src/pages/Polzzak/Polzzak.tsx
  src/pages/Search/SearchResult.tsx
Labels: 🛠️ Fix

#195 [Fix] 린트 오류 수정
  src/api/openAPI/utils/fetchContentDetail.ts
  src/components/Dialog/SlideUpDialog.tsx
  src/components/Map/MapHeader.tsx
  src/components/Map/ModalDetailContent.tsx
Labels: 🛠️ Fix

#196 [Fix] 린트 오류 수정
  src/api/openAPI/hooks/useGetFestival.ts
  src/components/Timeline/TimelineList.tsx
  src/pages/My/Edit/Email/Email.tsx
  src/pages/My/Edit/PhoneNumber/PhoneNumber.tsx
  src/pages/Polzzak/AddNEdit/AddNEdit.tsx
  src/pages/Register/Step3.tsx
  src/pages/Register/Step4.tsx
Labels: 🛠️ Fix

#197 [Deploy] 중간 배포 - 린트 오류 수정 완료
  src/api/openAPI/hooks/useGetFestival.ts
  src/api/openAPI/utils/fetchContentDetail.ts
  src/components/Dialog/SlideUpDialog.tsx
  src/components/Favorites/FavoritesList.tsx
  src/components/ListItem/ListItemCardById.tsx
  src/components/Map/MapHeader.tsx
  src/components/Map/ModalDetailContent.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/SlideUpModal.tsx
  src/components/Timeline/TimelineList.tsx
  src/hooks/useModalActions.ts
  src/pages/My/Edit/Email/Email.tsx
  src/pages/My/Edit/PhoneNumber/PhoneNumber.tsx
  src/pages/Polzzak/AddNEdit/AddNEdit.tsx
  src/pages/Polzzak/Polzzak.tsx
  src/pages/Register/Step3.tsx
  src/pages/Register/Step4.tsx
  src/pages/Search/Search.tsx
  src/pages/Search/SearchResult.tsx
  src/store/useEditStore.ts
  src/store/useModalStore.ts
  src/store/usePasswordStore.ts
Labels: 🌏 Deploy

#200 [Fix] 빌드 오류 수정
  src/api/openAPI/hooks/useContentDetail.ts
  src/lib/formatBr.tsx
  src/pages/Contents/ViewDetails.tsx
Labels: 🛠️ Fix

#201 [Fix] 빌드 후 오류 수정
  src/api/openAPI/utils/fetchContentDetail.ts
  src/components/Favorites/AddFavoriteCard.tsx
  src/components/ListItem/ListItemCardById.tsx
Labels: 🛠️ Fix

#202 [Deploy] 빌드 후 오류 수정
  src/api/openAPI/hooks/useContentDetail.ts
  src/api/openAPI/utils/fetchContentDetail.ts
  src/components/Favorites/AddFavoriteCard.tsx
  src/components/ListItem/ListItemCardById.tsx
  src/lib/formatBr.tsx
  src/pages/Contents/ViewDetails.tsx
Labels: 🌏 Deploy

#207 [Feature] 폴짝 검색 기능 구현
  src/components/Polzzak/PolzzakList.tsx
  src/hooks/useDebounce.ts
  src/pages/Polzzak/Polzzak.tsx
Labels: ✒️ Modify, ✅ Feature

#210 [Refactor] 즐겨찾기 페이지 성능 개선
  src/api/openAPI/utils/fetchImage.ts
  src/components/Favorites/AddFavoriteCard.tsx
  src/components/Favorites/FavoriteCard.tsx
  src/components/Favorites/FavoriteCards.tsx
  src/components/Favorites/FavoritesList.tsx
  src/components/ListItem/ListItemCardById.tsx
  src/pages/My/Favorites/Favorites.tsx
  src/pages/My/Favorites/FavoritesDetails.tsx
  src/store/useFavoritesStore.ts
Labels: ♻️ Refactor, ✒️ Modify, 🛠️ Fix, ⛔ Remove

#213 [Feature] 지도 검색 기능
  public/icons/cultural.png
  public/icons/favorite.png
  public/icons/festival.png
  public/icons/food.png
  public/icons/hotels.png
  public/icons/leports.png
  public/icons/polzzak.png
  public/icons/shopping.png
  public/icons/tour.png
  public/images/attraction.png
  public/images/favorite.png
  public/images/festival.png
  public/images/restaurant.png
  public/marker/cultural.svg
  public/marker/favorite.svg
  public/marker/festival.svg
  public/marker/food.svg
  public/marker/hotels.svg
  public/marker/leports.svg
  public/marker/map_cultural.svg
  public/marker/map_favorite.svg
  public/marker/map_festival.svg
  public/marker/map_food.svg
  public/marker/map_hotels.svg
  public/marker/map_leports.svg
  public/marker/map_marker.svg
  public/marker/map_shopping.svg
  public/marker/map_tour.svg
  public/marker/polzzak.svg
  public/marker/shopping.svg
  public/marker/tour.svg
  src/api/openAPI/hooks/map/useGetNearData.ts
  src/api/openAPI/hooks/map/useGetNearKeywordList.ts
  src/components/Category/Category.tsx
  src/components/Dialog/SlideUpDialog.tsx
  src/components/Map/MapHeader.tsx
  src/pages/Map/Map.tsx
  src/pages/NotFound.tsx
  src/styles/globals.css
Labels: ✒️ Modify, ✅ Feature

#216 [Fix] MapHeader 관련 수정
  src/components/Map/MapHeader.tsx
Labels: 🛠️ Fix

#218 [Feature] 폴짝 이미지 기능 구현
  src/components/Chip/Chip.tsx
  src/components/Input/ImageCropper.tsx
  src/components/Input/Input.tsx
  src/components/Polzzak/PolzzakListItem.tsx
  src/components/Timeline/Plan.tsx
  src/pages/Polzzak/AddNEdit/AddNEdit.tsx
  src/pages/Polzzak/Polzzak.tsx
  src/pages/Polzzak/Schedule/Schedule.tsx
  src/store/usePolzzakStroe.ts
Labels: ♻️ Refactor, ✒️ Modify, ⛔ Remove

#220 [Feature] 홈 기능 구현
  src/api/openAPI/hooks/useContentDetail.ts
  src/api/openAPI/hooks/useGetDetailCommon.ts
  src/api/openAPI/hooks/useGetFestival.ts
  src/api/openAPI/utils/fetchContentDetail.ts
  src/api/openAPI/utils/fetchHomeTheme.ts
  src/components/Category/Category.tsx
  src/components/Header/Header.tsx
  src/components/Home/CarouselThemes.tsx
  src/components/Home/CarouselVisual.tsx
  src/components/Home/ThemeItemCard.tsx
  src/layouts/RootLayout.tsx
  src/mockData/ListItemDummyData.tsx
  src/mockData/ScheduleDummyData.tsx
  src/pages/Home/Home.tsx
  src/pages/Polzzak/AddNEdit/AddNEdit.tsx
Labels: ♻️ Refactor, ✒️ Modify, ✅ Feature, ✂️ Rename, ⛔ Remove

#222 [Refactor] search 페이지
  src/api/openAPI/utils/fetchSearchList.ts
  src/components/Chip/Chip.tsx
  src/components/ListItem/ListItem.tsx
  src/components/Modal/SlideUpModal.tsx
  src/components/Search/DateSelector/DateSelector.tsx
  src/components/Search/KeywordInput/KeywordInput.tsx
  src/components/Search/RegionSelection/RegionSelection.tsx
  src/components/Search/SearchButton/SearchButton.tsx
  src/components/Search/ThemeSelection/ThemeSelection.tsx
  src/components/SortDropdown/Dropdown.tsx
  src/components/SortDropdown/DropdownCustom.tsx
  src/hooks/useModalActions.ts
  src/mockData/SortDropdownData.tsx
  src/pages/Search/Search.tsx
  src/pages/Search/SearchResult.tsx
  src/store/useSearchStore.ts
  src/styles/globals.css
Labels: ♻️ Refactor, ✒️ Modify, ✅ Feature

#225 [Fix] SearchResult 페이지
  src/pages/Search/SearchResult.tsx
Labels: 🛠️ Fix

#233 [Fix] 지도 빌드 오류 수정
  src/api/openAPI/utils/fetchMapSearchList.ts
  src/components/Map/MapMarkerList.tsx
  src/components/Map/ModalContent.tsx
  src/pages/Map/Map.tsx
  src/types/mapDataType.ts
Labels: ✒️ Modify, 🛠️ Fix

#235 [Feature] SearchResult 더보기 기능 구현
  src/api/openAPI/utils/fetchContentDetail.ts
  src/api/openAPI/utils/fetchSearchList.ts
  src/components/Search/SearchButton/SearchButton.tsx
  src/pages/Search/SearchResult.tsx
  src/store/useSearchStore.ts
Labels: ✅ Feature

#239 [Fix] fetchSearchList
  src/api/openAPI/utils/fetchSearchList.ts
Labels: 🛠️ Fix

#244 [Feature] 즐겨찾기, 폴짝 추가 기능 구현
  src/components/Dialog/FavoriteDialog.tsx
  src/components/Input/RadioGroup.tsx
  src/components/Input/Select.tsx
  src/components/Input/SelectMenu.tsx
  src/components/Modal/SlideUpModal.tsx
  src/components/UserMenu/UserMenu.tsx
  src/lib/dateUtils.ts
  src/mockData/ScheduleDummyData.tsx
  src/pages/Contents/ViewDetails.tsx
Labels: ✒️ Modify, ✅ Feature

#246 [Feature] Search 페이지
  src/api/openAPI/utils/fetchSearchList.ts
  src/components/Search/ThemeSelection/ThemeSelection.tsx
Labels: ✅ Feature, 🛠️ Fix

#249 [Modify] api 주소 변경(추가)
  src/api/openAPI/utils/fetchContentDetail.ts
  src/api/openAPI/utils/fetchSearchList.ts
Labels: ✒️ Modify

#252 [Modify] 지도 페이지: 찜 기능 구현
  src/api/openAPI/utils/fetchImage.ts
  src/components/Dialog/FavoriteDialog.tsx
  src/components/Favorites/FavoriteCards.tsx
  src/components/Favorites/FavoritesList.tsx
  src/components/ListItem/ListItemCardById.tsx
  src/components/Map/ModalContent.tsx
  src/components/Toast/Toast.tsx
  src/hooks/useFavoriteCheck.ts
  src/hooks/useFavoriteFolderId.ts
  src/lib/getFavoriteFolderId.ts
  src/lib/removeFavorite.ts
  src/pages/Contents/ViewDetails.tsx
  src/pages/My/Favorites/Favorites.tsx
  src/pages/My/Favorites/FavoritesDetails.tsx
Labels: ♻️ Refactor, ✒️ Modify, ✂️ Rename
