Repository polzzak-by-nowashgirls/polzzak, pull requests merged in 2025-04, with the labels that each got.

#95 [Feature] 로그인 및 스플래시 레이아웃
  public/favicon.ico
  public/images/rabbit_face.png
  public/images/splash.png
  src/components/RabbitFace/RabbitFace.tsx
  src/layouts/RootLayout.tsx
  src/pages/Login/Login.tsx
  src/pages/Splash/Splash.tsx
  src/pages/index.ts
  src/router.tsx
Labels: ✅ Feature

#97 [Feature] 로딩스피너 제작(진행 중)
  public/images/carrot.svg
  public/images/rabbit.svg
  src/components/HomeThemes/HomeThemes.tsx
  src/components/HomeThemes/ThemeItemListCard.tsx
  src/components/LoadingSpinner/LoadingSpinner.tsx
  src/components/LoadingSpinner/style.css
Labels: ✒️ Modify, ✅ Feature

#99 [Modify] 셀렉트메뉴 컴포넌트 수정
  src/components/Input/SelectMenu.tsx
Labels: ✒️ Modify

#102 [Feature] 폴짝 페이지
  src/components/Chip/Chip.tsx
  src/components/Input/Input.tsx
  src/components/Modal/Dimd.tsx
  src/components/Modal/SlideUpModal.tsx
  src/layouts/RootLayout.tsx
  src/pages/Polzzak/Add/Add.tsx
  src/pages/Polzzak/Polzzak.tsx
  src/pages/Polzzak/index.ts
  src/router.tsx
Labels: ♻️ Refactor, ✒️ Modify, ✅ Feature

#105 [Feature] 회원가입 페이지 레이아웃 제작
  src/components/Register/RegisterStep.tsx
  src/hooks/useModalActions.ts
  src/layouts/RootLayout.tsx
  src/pages/Register/Register.tsx
  src/pages/Register/Step1.tsx
  src/pages/Register/Step2.tsx
  src/pages/Register/Step3.tsx
  src/pages/Register/Step4.tsx
  src/pages/Register/Step5.tsx
  src/pages/Register/StepPage.tsx
  src/pages/Register/index.ts
  src/router.tsx
Labels: ✅ Feature

#109 [Modify] 마이페이지
  src/pages/My/Edit/index.ts
  src/router.tsx
Labels: ✒️ Modify

#111 [Modify] 컴포넌트 수정
  public/images/visual_1.png
  public/images/visual_2.png
  public/images/visual_3.png
  src/components/Button/ButtonVariants.tsx
  src/components/Carousel/VisualCarousel.tsx
  src/components/RabbitFace/RabbitFace.tsx
  src/layouts/RootLayout.tsx
Labels: ✒️ Modify

#112 [Feature] Not Found 페이지 제작
  src/pages/NotFound.tsx
  src/pages/Register/Step1.tsx
  src/pages/Register/Step2.tsx
Labels: ✅ Feature

#113 [Feature] 홈 레이아웃
  src/components/Home/Carousel.tsx
  src/components/Home/CarouselThemes.tsx
  src/components/Home/CarouselVisual.tsx
  src/components/Home/ThemeItemCard.tsx
  src/components/NavMenu/NavMenu.tsx
  src/pages/Home/Home.tsx
Labels: ✒️ Modify, ✅ Feature

#115 [Modify] 스플래시, 로그인 화면 수정
  public/fonts/ownglyphDah.ttf
  public/images/pattern.png
  src/components/RabbitFace/RabbitFace.tsx
  src/layouts/RootLayout.tsx
  src/pages/Login/Login.tsx
  src/pages/Splash/Splash.tsx
  src/styles/globals.css
  tailwind.config.ts
  tsconfig.app.json
Labels: ✒️ Modify

#119 [Feature] 목록 상세 레이아웃
  src/components/Contents/Details.tsx
  src/layouts/RootLayout.tsx
  src/pages/Contents/Contents.tsx
  src/pages/Contents/ViewDetails.tsx
  src/pages/Register/StepPage.tsx
  src/pages/index.ts
  src/router.tsx
Labels: ♻️ Refactor, ✒️ Modify, ✅ Feature

#120 [Feature] 즐겨찾기 레이아웃
  src/components/BookmarkFolder/AddBookmarkFolder.tsx
  src/components/BookmarkFolder/BookmarkFolder.tsx
  src/components/BookmarkFolder/BookmarkFolderCard.tsx
  src/components/BookmarkFolder/BookmarkFolderList.tsx
  src/components/Header/Header.tsx
  src/components/UserMenu/UserMenu.tsx
  src/layouts/RootLayout.tsx
  src/pages/My/Bookmark.tsx
  src/pages/My/My.tsx
  src/pages/index.ts
  src/router.tsx
  src/store/useModalStore.ts
Labels: ✅ Feature

#121 [Feature] 검색/폴짝추가/폴짝편집 페이지 레이아웃, Chip컴포넌트
  src/components/Chip/Chip.tsx
  src/components/Polzzak/PolzzakListItem.tsx
  src/pages/Polzzak/Edit/Edit.tsx
  src/pages/Polzzak/index.ts
  src/pages/Search/Search.tsx
  src/router.tsx
Labels: ✒️ Modify, ✅ Feature

#125 [Feature] 폴짝 상세 레이아웃
  src/components/Timeline/TimelineList.tsx
  src/components/Timeline/TimelineSchedule.tsx
  src/mockData/PolzzakItemDummyData.tsx
  src/mockData/PolzzakListDummyData.tsx
  src/pages/Polzzak/Schedule/Schedule.tsx
  src/pages/Polzzak/index.ts
  src/router.tsx
Labels: ✅ Feature

#127 [Feature] 목록 레이아웃
  src/components/ListItem/ListItem.tsx
  src/pages/NotFound.tsx
  src/pages/Search/SearchResult.tsx
  src/router.tsx
  src/vite-env.d.ts
Labels: ✒️ Modify, ✅ Feature

#130 [Modify] 데이터별 헤더 타이틀 변경
  src/components/Input/Input.tsx
  src/components/Input/Select.tsx
  src/components/Input/Textarea.tsx
  src/layouts/RootLayout.tsx
  src/pages/Contents/ViewDetails.tsx
  src/pages/Polzzak/Schedule/Schedule.tsx
  src/store/useHeaderStore.ts
Labels: ✒️ Modify, ✅ Feature

#132 [Fix] 정렬 드롭다운 컴포넌트 이슈 해결
  src/components/Button/ButtonVariants.tsx
  src/components/SortDropdown/Dropdown.tsx
  src/components/SortDropdown/DropdownCustom.tsx
Labels: ✒️ Modify, 🛠️ Fix

#131 [Chore] Supabase
  package.json
  pnpm-lock.yaml
  src/api/index.ts
  src/api/supabase/hooks/index.ts
  src/api/supabase/hooks/useGetTable.ts
  src/api/supabase/index.ts
Labels: ✅ Feature, 🗃️ Chore

#135 [Chore] open API 세팅 및 함수 생성
  src/api/openAPI/index.ts
  src/api/openAPI/useGetAreaCode.ts
Labels: ✅ Feature, 🗃️ Chore

#136 [Modify] 레이아웃 수정
  src/components/Button/ButtonVariants.tsx
  src/components/Input/Input.tsx
  src/components/Input/Select.tsx
  src/components/Input/Textarea.tsx
  src/components/Modal/AlertModal.tsx
  src/pages/My/Edit/Email/Email.tsx
  src/pages/My/Edit/NickName/NickName.tsx
  src/pages/My/Edit/Password/Password.tsx
  src/pages/NotFound.tsx
  src/pages/Register/Step3.tsx
  src/pages/Register/Step5.tsx
  src/pages/Search/Search.tsx
Labels: ✒️ Modify

#138 [Feature] 반려동물 동반 여행 정보 데이터 가져오기
  src/api/openAPI/hooks/useGetDetailPetTour.ts
Labels: ✅ Feature

#144 [Feature] 서비스 분류 코드 조회 데이터 가져오기
  src/api/openAPI/hooks/useGetCategoryCode.ts
  src/api/openAPI/hooks/useGetDetailPetTour.ts
Labels: ✒️ Modify, ✅ Feature

#143 [Feature] openAPI 공통 정보 조회
  src/api/openAPI/hooks/useGetAreaCode.ts
  src/api/openAPI/hooks/userGetDetailCommon.ts
  src/api/openAPI/index.ts
  tsconfig.app.json
Labels: ♻️ Refactor, ✅ Feature, 🛠️ Fix

#146 [Feature] 지도 페이지 레이아웃
  src/components/Chip/Chip.tsx
  src/components/MapHeader/MapHeader.tsx
  src/components/Modal/Dimd.tsx
  src/components/Modal/SlideUpModal.tsx
  src/layouts/RootLayout.tsx
  src/pages/Map/Map.tsx
  src/router.tsx
  src/store/useModalStore.ts
Labels: ✒️ Modify, ✅ Feature

#142 [Feature] 행사 정보 데이터 가져오기
  src/api/openAPI/hooks/useGetFestival.ts
  src/layouts/RootLayout.tsx
Labels: ✅ Feature

#149 [Feature] 로그인 기능 구현
  src/components/Modal/AlertModal.tsx
  src/hooks/useModalActions.ts
  src/lib/validatePassword.ts
  src/lib/validationId.ts
  src/pages/Login/Login.tsx
  src/store/useModalStore.ts
  src/styles/globals.css
Labels: ✒️ Modify, ✅ Feature

#152 [Chore] 프록시 설정
  src/api/openAPI/hooks/useGetAreaCode.ts
  src/api/openAPI/hooks/useGetCategoryCode.ts
  src/api/openAPI/hooks/useGetDetailPetTour.ts
  src/api/openAPI/hooks/useGetFestival.ts
  src/api/openAPI/hooks/userGetDetailCommon.ts
  src/api/openAPI/useGetAreaCode.ts
  vite.config.ts
Labels: ✒️ Modify, 🗃️ Chore, ⛔ Remove

#153 [Feature] 즐겨찾기 리스트 페이지
  src/components/BookmarkFolder/AddBookmarkFolder.tsx
  src/components/BookmarkFolder/BookmarkFolder.tsx
  src/components/BookmarkFolder/BookmarkFolderCard.tsx
  src/components/BookmarkFolder/BookmarkFolderList.tsx
  src/components/Category/Category.tsx
  src/components/Header/Header.tsx
  src/components/Input/Input.tsx
  src/components/Modal/SlideUpModal.tsx
  src/hooks/useModalActions.ts
  src/mockData/ListItemDummyData.tsx
  src/pages/My/Bookmark.tsx
  src/pages/RequireLogin.tsx
  src/store/useBookmarkStore.ts
  src/store/useHeaderStore.ts
  src/store/useModalStore.ts
Labels: ♻️ Refactor, ✒️ Modify, ✅ Feature

#156 [Refactor] Chip 컴포넌트
  src/components/Chip/Chip.tsx
Labels: ♻️ Refactor

#157 [Rename] 즐겨찾기명 변경
  src/components/BookmarkFolder/BookmarkFolderList.tsx
  src/components/Category/Category.tsx
  src/components/Favorites/AddFavoriteCard.tsx
  src/components/Favorites/FavoriteCard.tsx
  src/components/Favorites/Favorites.tsx
  src/components/Favorites/FavoritesList.tsx
  src/components/Loader/Loader.tsx
  src/components/LoadingSpinner/style.css
  src/hooks/useModalActions.ts
  src/pages/My/Favorites.tsx
  src/pages/Polzzak/Schedule/Schedule.tsx
  src/pages/index.ts
  src/router.tsx
  src/store/useFavoritesStore.ts
Labels: ✒️ Modify, ✂️ Rename

#160 [Feature] Dialog 컴포넌트 제작
  src/components/Dialog/AlertDialog.tsx
  src/components/Dialog/SlideUpDialog.tsx
  src/store/useModalStore.ts
Labels: ✅ Feature

#162 [Modify] Dialog 컴포넌트 수정
  src/components/Dialog/AlertDialog.tsx
  src/components/Dialog/SlideUpDialog.tsx
  src/store/useDialogStore.ts
  src/store/useModalStore.ts
Labels: ♻️ Refactor, ✒️ Modify, ✅ Feature

#163 [Feature] 지도 필터링 기능 구현
  public/marker/map_marker.svg
  public/marker/map_marker_favorite.svg
  public/marker/map_marker_festival.svg
  public/marker/map_marker_food.svg
  public/marker/map_marker_polzzak.svg
  public/marker/map_marker_tour.svg
  public/marker/my_location.svg
  src/api/openAPI/hooks/map/useGetNearData.ts
  src/api/openAPI/hooks/map/useGetNearFestivalList.ts
  src/api/openAPI/hooks/map/useGetNearFoodList.ts
  src/api/openAPI/hooks/map/useGetNearTourList.ts
  src/components/Map/MapHeader.tsx
  src/components/Map/ModalContent.tsx
  src/components/MapHeader/MapHeader.tsx
  src/pages/Map/Map.tsx
Labels: ✅ Feature

#166 [Feature] 즐겨찾기 상세 리스트
  src/components/Favorites/AddFavoriteCard.tsx
  src/components/Favorites/FavoriteCard.tsx
  src/components/Favorites/FavoriteCards.tsx
  src/components/Favorites/Favorites.tsx
  src/components/Favorites/FavoritesList.tsx
  src/components/Input/Input.tsx
  src/components/ListItem/ListItem.tsx
  src/components/RabbitFace/RabbitFace.tsx
  src/layouts/RootLayout.tsx
  src/pages/Login/Login.tsx
  src/pages/My/Favorites.tsx
  src/pages/My/Favorites/Favorites.tsx
  src/pages/My/Favorites/FavoritesDetails.tsx
  src/pages/My/Favorites/index.ts
  src/pages/My/My.tsx
  src/pages/NotFound.tsx
  src/pages/index.ts
  src/router.tsx
  src/store/useFavoritesStore.ts
  src/store/useToastStore.ts
Labels: ♻️ Refactor, ✒️ Modify, ✅ Feature

#168 [Feature] 회원가입 기능
  src/api/supabase/hooks/updateNickname.ts
  src/components/Input/SelectMenu.tsx
  src/components/Modal/SlideUpModal.tsx
  src/hooks/register/useUserUpdate.ts
  src/hooks/useModalActions.ts
  src/pages/Register/Register.tsx
  src/pages/Register/Step1.tsx
  src/pages/Register/Step2.tsx
  src/pages/Register/Step3.tsx
  src/pages/Register/Step4.tsx
  src/pages/Register/Step5.tsx
  src/store/useModalStore.ts
  src/store/useRegisterStore.ts
Labels: ✅ Feature

#171 [Feature] content id로 데이터 불러오기 - axios 사용
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/openAPI/client.ts
  src/api/openAPI/hooks/useContentDetail.ts
  src/api/openAPI/hooks/useGetDetailCommon.ts
  src/api/openAPI/index.ts
  src/api/openAPI/utils/fetchContentDetail.ts
  src/api/openAPI/utils/fetchImage.ts
  src/api/supabase/utils/getLikesAndReviews.ts
  src/api/supabase/utils/index.ts
  src/components/Favorites/FavoriteCards.tsx
  src/components/Favorites/FavoritesList.tsx
  src/components/ListItem/ListItemCardById.tsx
  src/pages/My/Favorites/FavoritesDetails.tsx
Labels: ✒️ Modify, ✅ Feature, ✂️ Rename, 🗃️ Chore, 🛠️ Fix, ⛔ Remove

#173 [Feature] 즐겨찾기 찜 기능 구현
  package.json
  pnpm-lock.yaml
  src/api/openAPI/client.ts
  src/api/openAPI/utils/fetchImage.ts
  src/components/Favorites/FavoritesList.tsx
  src/components/ListItem/ListItemCardById.tsx
  src/pages/Home/Home.tsx
  src/pages/My/Favorites/Favorites.tsx
  src/pages/My/Favorites/FavoritesDetails.tsx
  src/pages/Polzzak/Polzzak.tsx
Labels: ♻️ Refactor, ✒️ Modify, ✅ Feature
