Repository polzzak-by-nowashgirls/polzzak, pull requests merged in 2025-06, with the labels that each got.

#255 [Modify] viewDetail 수정
  src/api/openAPI/hooks/useGetDetailCommon.ts
  src/api/openAPI/utils/fetchSearchList.ts
  src/components/ListItem/ListItem.tsx
  src/components/Search/ThemeSelection/ThemeSelection.tsx
  src/pages/Contents/ViewDetails.tsx
Labels: ✒️ Modify, ✅ Feature

#257 [Modify] 지도 훅 관련 수정
  src/components/Dialog/MapDialog.tsx
  src/hooks/map/useFetchMarkers.ts
  src/hooks/map/useMapDialogEffect.ts
  src/hooks/map/useSyncFilterWithQuery.ts
  src/hooks/map/useSyncLocation.ts
Labels: ✒️ Modify

#261 [Feature] SearchResult페이지에 Loader 추가
  src/pages/Search/SearchResult.tsx
  src/store/useSearchStore.ts
Labels: ✅ Feature

#265 [Modify] viewDetails
  src/components/Contents/Details.tsx
Labels: ✒️ Modify

#269 [Modify] 즐겨찾기 폴더 및 폴짝 추가 페이지 수정
  src/components/Favorites/FavoriteCard.tsx
  src/pages/Polzzak/AddNEdit/AddNEdit.tsx
Labels: ✒️ Modify

#271 [Modify] 검색 목록 및 상세페이지 수정
  src/api/openAPI/utils/fetchContentDetail.ts
  src/api/openAPI/utils/fetchHomeTheme.ts
  src/components/Contents/Details.tsx
  src/components/Home/ThemeItemCard.tsx
  src/components/ListItem/ListItemCardById.tsx
  src/pages/Contents/ViewDetails.tsx
  src/pages/Home/Home.tsx
  src/pages/Search/SearchResult.tsx
Labels: ♻️ Refactor, ✒️ Modify

#274 [Refactor] 회원가입 리팩토링
  src/lib/getRandomNickname.ts
  src/lib/validationEmail.ts
  src/lib/validationId.ts
  src/lib/validationNickname.ts
  src/lib/validationPassword.ts
  src/lib/validationPhone.ts
  src/pages/Login/Login.tsx
  src/pages/Login/ResetPasswordCallback.tsx
  src/pages/My/Edit/Password/Password.tsx
  src/pages/Register/REGISTER_STEP.ts
  src/pages/Register/Register.tsx
  src/pages/Register/Step1.tsx
  src/pages/Register/Step2.tsx
  src/pages/Register/Step3.tsx
  src/pages/Register/Step4.tsx
  src/pages/Register/Step5.tsx
  src/pages/Register/StepPage.tsx
  src/pages/Register/index.ts
  src/router.tsx
Labels: ♻️ Refactor

#280 [Feature] 회원가입 이메일 인증 기능 구현
  src/layouts/RootLayout.tsx
  src/lib/validationEmail.ts
  src/pages/Login/FindEmail.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/ResetPassword.tsx
  src/pages/Login/ResetPasswordCallback.tsx
  src/pages/Register/REGISTER_STEP.ts
  src/pages/Register/Register.tsx
  src/pages/Register/SignUpCallback.tsx
  src/pages/Register/Step1.tsx
  src/pages/Register/Step2.tsx
  src/pages/Register/Step4.tsx
  src/pages/Register/Step5.tsx
  src/pages/Register/index.ts
  src/pages/index.ts
  src/router.tsx
Labels: 🛋️ Style, ✒️ Modify, ✅ Feature, ✂️ Rename

#282 [Feature] 나의 리뷰 페이지 생성
  src/api/openAPI/utils/fetchGetDetailCommon.ts
  src/api/supabase/utils/getLikesAndReviews.ts
  src/components/Contents/Details.tsx
  src/components/Contents/Review.tsx
  src/components/Dialog/FavoriteDialog.tsx
  src/components/Dialog/SlideUpDialog.tsx
  src/components/ListItem/ListItemCardById.tsx
  src/layouts/RootLayout.tsx
  src/lib/favorite.ts
  src/pages/My/Favorites/FavoritesDetails.tsx
  src/pages/My/MyReviews/MyReviews.tsx
  src/pages/index.ts
  src/router.tsx
  src/styles/globals.css
Labels: ♻️ Refactor, ✒️ Modify, ✅ Feature

#288 [Fix] 마이페이지 오류 수정
  src/api/supabase/hooks/updateEmail.ts
  src/api/supabase/hooks/updateNickname.ts
  src/hooks/register/useUserUpdate.ts
  src/hooks/useModalActions.ts
  src/pages/My/Edit/Password/Password.tsx
  src/pages/My/Edit/PhoneNumber/PhoneNumber.tsx
  src/store/useUserStore.ts
Labels: ♻️ Refactor, 🛠️ Fix

#289 [Refactor] 로그인/회원가입 관련 리팩토링
  src/components/Input/SelectMenu.tsx
  src/components/Input/Validation.tsx
  src/layouts/RootLayout.tsx
  src/lib/validationEmail.ts
  src/lib/validationId.ts
  src/lib/validationNickname.ts
  src/lib/validationPhone.ts
  src/pages/Login/FindEmail.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/ResetPassword.tsx
  src/pages/Login/ResetPasswordCallback.tsx
  src/pages/Register/REGISTER_STEP.ts
  src/pages/Register/Register.tsx
  src/pages/Register/SignUpCallback.tsx
  src/pages/Register/Step1.tsx
  src/pages/Register/Step2.tsx
  src/pages/Register/Step3.tsx
  src/pages/Register/Step4.tsx
  src/pages/Register/index.ts
  src/pages/index.ts
  src/router.tsx
Labels: 🛋️ Style, ♻️ Refactor, ✒️ Modify, ⛔ Remove

#291 [Refactor] 즐겨찾기 모달, 리뷰 페이지 수정
  src/components/Contents/Details.tsx
  src/components/Contents/Review.tsx
  src/components/Contents/ReviewList.tsx
  src/components/My/MenuItem.tsx
  src/pages/Contents/DetailReviews.tsx
  src/pages/Contents/ViewDetails.tsx
  src/pages/My/My.tsx
  src/pages/My/MyReviews/MyReviews.tsx
Labels: ♻️ Refactor, ✒️ Modify

#293 [Fix] 회원가입 인증 링크 진입 시 로그인 화면에서 emailValue가 초기화되는 문제
  src/pages/Login/Login.tsx
  src/pages/Register/Step3.tsx
Labels: 🛠️ Fix

#294 [Docs] 리드미 작성
  README.md
  src/components/Tabmenu/Tabmenu.tsx
  src/mockData/DetailsDummyData.tsx
  src/mockData/index.ts
Labels: 📋 Docs

#297 [Docs, Refactor] 오류 및 리드미 수정
  README.md
  src/components/Input/RadioGroup.tsx
  src/pages/Contents/ViewDetails.tsx
Labels: 📋 Docs, ♻️ Refactor

#303 [Docs] 주요 기능 추가
  README.md
  src/pages/Polzzak/AddNEdit/AddNEdit.tsx
Labels: 📋 Docs, ♻️ Refactor

#305 [Refactor] 리드미 및 폴짝 스타일 수정
  README.md
  public/images/1.png
  public/images/2.png
  public/images/3.png
  src/pages/My/MyReviews/MyReviews.tsx
  src/pages/Polzzak/AddNEdit/AddNEdit.tsx
Labels: 📋 Docs, ♻️ Refactor

#307 [Docs] 리드미 스택 및 헤더 수정
  README.md
  public/images/readme/search.png
Labels: 📋 Docs
