Repository polzzak-by-nowashgirls/polzzak, pull requests merged in 2025-03, with the labels that each got.

#3 [init] 프로젝트 초기세팅
  .gitignore
  .prettierrc.json
  README.md
  components.json
  eslint.config.js
  index.html
  package.json
  pnpm-lock.yaml
  public/polzzak.png
  src/App.tsx
  src/api/index.ts
  src/components/ui/button.tsx
  src/hooks/index.ts
  src/lib/utils.ts
  src/main.tsx
  src/mockData/index.ts
  src/store/index.ts
  src/styles/globals.css
  src/types/index.ts
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 🐣 Init

#7 [Feature] 페이지 라우터 추가
  .gitignore
  index.html
  public/favicon.ico
  public/polzzak.png
  src/App.tsx
  src/layouts/RootLayout.tsx
  src/main.tsx
  src/pages/Home/Home.tsx
  src/pages/Login/Login.tsx
  src/pages/Map/Map.tsx
  src/pages/My/My.tsx
  src/pages/NotFound.tsx
  src/pages/Polzzak/Polzzak.tsx
  src/pages/Register/Register.tsx
  src/pages/Search/Search.tsx
  src/pages/index.ts
  src/router.tsx
Labels: ✅ Feature

#10 [Feature] 버튼 컴포넌트
  src/components/Button/button.tsx
  src/components/ui/button.tsx
  src/fonts/PretendardVariable.woff2
  src/lib/utils.ts
  src/styles/globals.css
  src/tailwind.config.ts
Labels: ✅ Feature

#11 [Feature] svg 파일 및 아이콘 컴포넌트 생성
  public/stack.svg
  src/components/Icon/Icon.tsx
Labels: ✅ Feature

#14 [Docs] PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📋 Docs

#15 [Feature] 홈-카테고리 컴포넌트
  public/images/attraction.png
  public/images/favorite.png
  public/images/festival.png
  public/images/restaurant.png
  src/components/Category/Category.tsx
  src/styles/globals.css
Labels: ✅ Feature

#18 [Modify] 버튼 컴포넌트 수정
  src/components/Button/button.tsx
Labels: ✒️ Modify

#24 [Modify] global.css 수정
  src/styles/globals.css
Labels: ✒️ Modify

#25 [Feature] 달력 컴포넌트
  package.json
  pnpm-lock.yaml
  src/components/Button/Button.tsx
  src/components/Button/ButtonVariants.tsx
  src/components/Button/button.tsx
  src/components/Calendar/Calendar.tsx
Labels: ✅ Feature

#27 [Feature] 회원가입 진행도 컴포넌트
  package.json
  pnpm-lock.yaml
  src/components/Register/RegisterStep.tsx
  src/components/Register/Step.tsx
  src/components/Register/progress.tsx
Labels: ✅ Feature

#28 [Feature] input 컴포넌트 생성
  package.json
  pnpm-lock.yaml
  src/components/Input/Input.tsx
  src/components/Input/Validation.tsx
  src/components/Label.tsx
  src/styles/globals.css
Labels: ✅ Feature

#30 [modify] 버튼 컴포넌트 수정
  src/components/Button/ButtonVariants.tsx
Labels: ✒️ Modify

#20 [Feature] 상세보기 설명
  src/components/Contents/Details.tsx
  src/mockData/DetailsDummyData.tsx
  src/mockData/index.ts
Labels: ✅ Feature

#35 [Feature] Textarea 컴포넌트
  src/components/Input/Textarea.tsx
Labels: ✅ Feature

#37 [Feature] 토스트 컴포넌트 제작
  src/components/Button/ButtonVariants.tsx
  src/components/Toast.tsx
  src/styles/globals.css
Labels: ✒️ Modify, ✅ Feature

#42 [Modify] Icon 컴포넌트 수정
  src/components/Icon/Icon.tsx
Labels: ✒️ Modify

#43 [Feature] 마이페이지 메뉴 컴포넌트
  src/components/Calendar/Calendar.tsx
  src/components/My/MenuItem.tsx
  src/components/Toast.tsx
Labels: ✒️ Modify, ✅ Feature

#46 [Feature] 정렬 드롭다운 버튼 컴포넌트
  package.json
  pnpm-lock.yaml
  src/components/SortDropdown/Dropdown.tsx
  src/components/SortDropdown/DropdownMenu.tsx
  src/components/SortDropdown/Sort.tsx
  src/mockData/SortDropdownData.tsx
  src/styles/globals.css
Labels: ✅ Feature

#47 [Feature] 리스트 아이템 컴포넌트 제작
  src/components/ListItem/ListItem.tsx
  src/mockData/ListItemDummyData.tsx
Labels: ✅ Feature

#49 [Feature] 마이페이지-프로필 컴포넌트
  src/components/Profile/Profile.tsx
  src/mockData/UserInfo.tsx
  src/mockData/index.ts
Labels: ✅ Feature

#50 [Feature] Radio 컴포넌트 추가
  package.json
  pnpm-lock.yaml
  src/components/Input/Input.tsx
  src/components/Input/RadioGroup.tsx
  src/components/Input/SelectMenu.tsx
  src/components/Label.tsx
  src/lib/dateUtils.ts
  src/mockData/ScheduleDummyData.tsx
Labels: ✒️ Modify, ✅ Feature

#55 [Feature] 캐러셀 컴포넌트
  package.json
  pnpm-lock.yaml
  public/images/visual_1.png
  public/images/visual_2.png
  public/images/visual_3.png
  src/components/Carousel/Carousel.tsx
  src/components/Carousel/VisualCarousel.tsx
Labels: ✅ Feature

#59 [Feature] 폴짝 목록 아이템 컴포넌트
  public/images/attraction.png
  public/images/favorite.png
  public/images/festival.png
  public/images/restaurant.png
  src/components/Polzzak/ListItem.tsx
  src/mockData/PolzzakListDummyData.tsx
Labels: ✅ Feature

#62 [Feature] Chip 컴포넌트
  src/components/Chip/Chip.tsx
Labels: ✅ Feature

#60 [Feature] GNB 컴포넌트 추가
  package.json
  pnpm-lock.yaml
  src/components/NavMenu/NavMenu.tsx
  src/router.tsx
Labels: ✅ Feature

#64 [Modify] 토스트, 마이페이지 메뉴 컴포넌트 수정
  src/App.tsx
  src/components/My/MenuItem.tsx
  src/components/Toast.tsx
  src/components/Toast/Toast.tsx
  src/hooks/useToast.ts
  src/pages/Login/Login.tsx
  src/pages/My/My.tsx
  src/store/useToastStore.ts
Labels: ✒️ Modify

#65 [Feature] Header 컴포넌트
  src/components/Header/Header.tsx
Labels: ✅ Feature

#67 [Modify] Category 컴포넌트
  src/components/Category/Category.tsx
Labels: ✒️ Modify

#68 [Modify] 폴짝 리스트 아이템 컴포넌트 수정
  src/components/Polzzak/ListItem.tsx
  src/components/Polzzak/PolzzakList.tsx
  src/components/Polzzak/PolzzakListItem.tsx
  src/mockData/PolzzakListDummyData.tsx
  src/pages/Polzzak/Polzzak.tsx
Labels: ✒️ Modify

#74 [Modify] svg 파일 및 아이콘 컴포넌트 수정
  public/stack.svg
  src/components/Icon/Icon.tsx
Labels: ✒️ Modify

#75 [Modify] 폰트 및 아이콘 관련 수정
  public/fonts/PretendardVariable.woff2
  src/components/Icon/Icon.tsx
  src/components/UserMenu/UserMenu.tsx
  src/fonts/PretendardVariable.woff2
  src/pages/My/My.tsx
  src/styles/globals.css
Labels: ✒️ Modify

#78 [Modify] 스프라이트 이미지 수정
  public/sprite.svg
  public/stack.svg
  src/components/Icon/Icon.tsx
Labels: ✒️ Modify, ✂️ Rename

#76 [Feature] 즐겨찾기 폴더 컴포넌트 제작
  src/components/BookmarkFolder/AddBookmarkFolder.tsx
  src/components/BookmarkFolder/BookmarkFolder.tsx
  src/components/BookmarkFolder/BookmarkFolderCard.tsx
  src/components/BookmarkFolder/BookmarkFolderList.tsx
  src/mockData/ScheduleDummyData.tsx
Labels: ✅ Feature

#79 [Modify] 달력 컴포넌트 외 다수 수정
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarCustom.tsx
  src/components/Carousel/Carousel.tsx
  src/components/Icon/Icon.tsx
  src/components/SortDropdown/Dropdown.tsx
  src/components/SortDropdown/DropdownCustom.tsx
Labels: ✒️ Modify

#83 [Feature] 체크박스 컴포넌트
  package.json
  pnpm-lock.yaml
  src/components/Checkbox/Checkbox.tsx
Labels: ✅ Feature, 🗃️ Chore

#82 [Feature] Modal 컴포넌트
  src/components/Modal/AlertModal.tsx
  src/components/Modal/Dimd.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/SlideUpModal.tsx
  src/hooks/useModalActions.ts
  src/store/useModalStore.ts
Labels: ✅ Feature

#84 [Feature] 타임라인 카드 및 리스트 컴포넌트 제작
  package.json
  pnpm-lock.yaml
  public/sprite.svg
  src/components/Timeline/TimelineCard.tsx
  src/components/Timeline/TimelineList.tsx
  src/mockData/PolzzakItemDummyData.tsx
Labels: ✒️ Modify, ✅ Feature

#90 [Feature] RootLayout 설정
  src/components/Header/Header.tsx
  src/components/NavMenu/NavMenu.tsx
  src/layouts/RootLayout.tsx
  src/styles/globals.css
Labels: ✒️ Modify, ✅ Feature

#92 [Feature] 홈 테마 섹션 컴포넌트 제작
  src/components/HomeThemes/HomeThemes.tsx
  src/components/HomeThemes/ThemeItemListCard.tsx
  src/mockData/ListItemDummyData.tsx
Labels: ✅ Feature
